theme: jekyll-theme-slate
title: Welcome to keamoradebe's homepage!
description: I am an Information Systems (Hons) graduate from Rhodes University. 
    This page will showcase the skills I have in software development. Feel free to keep an eye on my project updates.
